# Generated by Django 4.2.3 on 2023-07-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_spot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='destination',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='main_app.destination'),
        ),
    ]
